update ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -53,12 +53,6 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
-      - name: Install Docker Compose
-        run: |
-          sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-          sudo chmod +x /usr/local/bin/docker-compose
-          docker-compose --version
-
       - name: Build Docker image
         uses: docker/build-push-action@v4
         with:
@@ -69,7 +63,18 @@ jobs:
 
       - name: Test Docker container
         run: |
-          docker-compose up -d
-          sleep 10
-          curl --fail http://localhost:3001 || exit 1
-          docker-compose down
+          docker run -d -p 3001:3000 test-pipeline-express:test
+          echo "Waiting for application to start..."
+          for i in {1..30}; do
+            if curl -s http://localhost:3001/users; then
+              echo "Application is up!"
+              break
+            fi
+            echo "Attempt $i: Application not ready yet..."
+            sleep 2
+            if [ $i -eq 30 ]; then
+              echo "Application failed to start"
+              exit 1
+            fi
+          done
+          docker ps -q | xargs -r docker stop
